image = "/users/rmeli/git/work/containers/cscs/mtt/mtt-v1.squashfs"
mounts = ["/capstor/store/cscs/cscs/csstaff/rmeli/:/capstor/store/cscs/cscs/csstaff/rmeli/"]
workdir = "/capstor/store/cscs/cscs/csstaff/rmeli/support/dtisi-65738/"

[annotations]
com.hooks.cxi.enabled = "true"
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
